### ISSUE TITLE
Current version doesn't run

### ISSUE THREAD

**Issue by CfGit12** [kotlin-hands-on/web-app-react-kotlin-js-gradle#21]
Just checked out the project and tried to run browserDevelopmentRun but it fails with:

[webpack-cli] TypeError: cli.isMultipleCompiler is not a function
[webpack-cli] TypeError: cli.isMultipleCompiler is not a function
    at Command.<anonymous> (/Users/Charles.Flynn/IdeaProjects/CF/web-app-react-kotlin-js-gradle/build/js/node_modules/@webpack-cli/serve/lib/index.js:146:35)
    at async Promise.all (index 1)
    at async Command.<anonymous> (/Users/Charles.Flynn/IdeaProjects/CF/web-app-react-kotlin-js-gradle/build/js/node_modules/webpack-cli/lib/webpack-cli.js:1687:7)

I've been able to fix it by bumping the webpack version as follows in build.gradle.kts:

```kotlin
rootProject.plugins.withType(org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootPlugin::class.java) {
    rootProject.the<org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootExtension>().versions.webpackCli.version = "4.10.0"
}
```

Putting this here in case anyone else comes across it, and so it can be fixed to prevent others encountering this.

**Comment by SebastianAigner** [comment]
Thanks for the report, @CfGit12 . Indeed, there is a problem that's currently affecting other Kotlin/JS projects as well: https://youtrack.jetbrains.com/issue/KT-52776/ and https://youtrack.jetbrains.com/issue/KT-52890.

We'll update this tutorial with Kotlin 1.7.10, which also addresses this problem.

**Comment by SebastianAigner** [comment]
Another snippet to downgrade the webpack version until we've addressed this:
```
rootProject.extensions.configure<org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootExtension> {
    versions.webpackCli.version = "4.10.0"
}
```
