### ISSUE TITLE
Can't run the fork (Error: listen EACCES: permission denied)

### ISSUE THREAD

**Issue by PeredurOmega** [kotlin-hands-on/web-app-react-kotlin-js-gradle#3]
Hi! I am trying to get started with Kotlin/JS and I therefore followed this step by step tutorial : https://play.kotlinlang.org/hands-on/Building%20Web%20Applications%20with%20React%20and%20Kotlin%20JS/02_Setting_up. However as I couldn't get it working, I forked this repo and try to run it. Unfortunately, every time I run this project I have the same error and I can't find a way to deal with it:

> Error: listen EACCES: permission denied 127.0.0.1:8080
>     at Server.setupListenHandle [as _listen2] (net.js:1284:19)
>     at listenInCluster (net.js:1349:12)
>     at GetAddrInfoReqWrap.doListen [as callback] (net.js:1488:7)
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:65:10)
> Emitted 'error' event on Server instance at:
>     at emitErrorNT (net.js:1328:8)
>     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
>   code: 'EACCES',
>   errno: 'EACCES',
>   syscall: 'listen',
>   address: '127.0.0.1',
>   port: 8080
> }
> :browserDevelopmentRun (Thread[Execution worker for ':',5,main]) completed. Took 0.926 secs.
> 
> FAILURE: Build failed with an exception.

I tried to change the port by doing the following : 
`devServer = KotlinWebpackConfig.DevServer(
               port = 3000,
               contentBase = listOf("$buildDir/processedResources/frontend/main")
           )`

This way I dont't have "permission denied" but I have an other error indicating "Cannot GET /" on the HTML page. Therefore I was wondering if you had any idea on what might be the issue here.

I also tried to run it on Firefox / Vivaldi / Chrome but it doesn't seem to change anything for me.

Thanks for your help!

**Comment by PeredurOmega** [comment]
So I solved my issue by using this code:
`
devServer = KotlinWebpackConfig.DevServer( port = 3000, contentBase = listOf("$buildDir/processedResources/Js/main") )
`
It seems that I probably had an other service already using 8080 and that it was causing "Error: listen EACCES: permission denied".

Using the port 3000 works fine.
